url: 'https://germanvillarreal.github.io'
baseurl: '/gnarweb/'
# Site settings
title: Vancouver Snowboard Lessons
email: vo.german@gmail.com
description: Hey! Are you looking to learn how to Snowboard? I'm a certified Instructor who loves sharing my passion. Check out my bio, and contact me for rates!


# Build settings
markdown: kramdown
permalink: pretty