url: https://germanvillarreal.github.io
baseurl: /gnarweb/
# Site settings
title: Vancouver Snowboard Lessons
email: vo.german@gmail.com
description: "Hey! Are you looking to learn how to Snowboard? I'm a certified Instructor who loves sharing my passion. Check out my bio, and contact me for rates!"


# Team names, titles and social links
people:
- name: German Villarreal
  pic: 1
  position: Snowboard Instructor


# Build settings
markdown: kramdown
permalink: pretty